services:
  api:
    build: .
    restart: always
    ports: 
      - '8000:8000'
    # environment:
    #   PORT: 8000
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost:${PORT}/flask-health-check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    command: gunicorn -w 3 -t 60 -b 0.0.0.0:8000 app:app

# for nginx see: https://github.com/docker/awesome-compose/tree/master/nginx-wsgi-flask